name: example
description: Example app for Unicorn UX.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.10.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  unicornux:
    path: ../
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
