name: unicornux
description: UI components for designers committed to elegance.
version: 1.0.0
homepage: https://github.com/iamtheblackunicorn/unicornux
environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
  loading_animations: ^2.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  loading_animations: ^2.2.0
flutter:
  uses-material-design: true
